(function(){function toggleElem(el){var isActive,extraTogglerClasses,dataTogglerClasses;if(el.getAttribute('data-static')==='true'){return}
isActive=el.classList.contains('toggler-active');extraTogglerClasses=['toggler-active'];dataTogglerClasses=el.getAttribute('data-classes');if(dataTogglerClasses){extraTogglerClasses=extraTogglerClasses.concat(dataTogglerClasses.split(' '))}
el.classList[isActive?'remove':'add'].apply(el.classList,extraTogglerClasses);el.setAttribute('aria-expanded',!isActive)}
function setState(newState,_toggler,_target){var targetId,isActive=!newState,otherTogglers,o,rememberClosed=_toggler.getAttribute('data-remember-closed');toggleElem(_toggler);_target.style.display=isActive?'none':'block';_target.classList[isActive?'remove':'add']('toggler-target-active','fadeIn');targetId=_toggler.getAttribute('data-toggle-target');if(rememberClosed){Cookies.set(_toggler.getAttribute('data-toggle-target'),'closed')}
otherTogglers=document.querySelectorAll('[data-toggle-target="'+targetId+'"]:not([data-static="true"])');if(otherTogglers.length>0){for(o=0;o<otherTogglers.length;o++){if(otherTogglers[o]!==_toggler){toggleElem(otherTogglers[o])}}}}
var togglers=document.getElementsByClassName('toggler');for(var i=0;i<togglers.length;i++){togglers[i].addEventListener('click',function(e){var isActive=this.classList.contains('toggler-active'),_target=document.getElementById(this.getAttribute('data-toggle-target'));setState(!isActive,this,_target)});togglers[i].addEventListener('keypress',function(e){if(e.which==13){var isActive=this.classList.contains('toggler-active'),_target=document.getElementById(this.getAttribute('data-toggle-target'));setState(!isActive,this,_target)}})}
if(window.document.documentMode){return}
function scrollTo(element){window.scroll({behavior:'smooth',left:0,top:window.pageYOffset+element.getBoundingClientRect().top-80,})}
var elements=document.querySelectorAll('a[href*="#"]:not([href="#"]):not([data-toggle="tab"])');elements=Array.from(elements).concat(Array.from(document.querySelectorAll('a:not([href])')));for(var j=0;j<elements.length;j++){elements[j].addEventListener('click',function(e){var el=null;if(this.namespaceURI==='http://www.w3.org/2000/svg'&&this.href.baseVal[0]==='#'){el=document.getElementById(this.href.baseVal.slice(1));if(el){e.preventDefault();scrollTo(el);return!1}}else if(window.location.pathname.replace(/^\//,'')===this.pathname.replace(/^\//,'')&&window.location.hostname===this.hostname){el=document.getElementById(this.hash.slice(1));if(el){scrollTo(el)}}
return!0})}})()